ALTER TABLE public.challenges
ADD COLUMN IF NOT EXISTS escalation_stage INT,
ADD COLUMN IF NOT EXISTS escalation_status VARCHAR(50),
ADD COLUMN IF NOT EXISTS statewide_bidding_open BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS statewide_bidding_geofence_removed BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE public.projects
ADD COLUMN IF NOT EXISTS nep_credits INT NOT NULL DEFAULT 4,
ADD COLUMN IF NOT EXISTS deliverables_expanded BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.projects
ADD COLUMN IF NOT EXISTS spares_kit_months INT NOT NULL DEFAULT 12;
