import { AlertTriangle, CheckCircle2, Radio, ShieldCheck, Wrench } from 'lucide-react';

const installations = [
  { id: 'JAG-PLM-0082', title: 'Solar defluoridation unit', site: 'Lesliganj, Palamu', day: 32, health: 99.1, alarm: 'Stable', updated: '6 min ago' },
  { id: 'JAG-KHT-0014', title: 'Solar lac cold storage', site: 'Torpa, Khunti', day: 24, health: 98.4, alarm: 'Stable', updated: '12 min ago' },
  { id: 'JAG-ESG-0147', title: 'Forest hamlet microgrid', site: 'Ghatshila, East Singhbhum', day: 17, health: 87.6, alarm: 'Watch', updated: '2 min ago' },
];

export default function MaintenancePage() {
  return (
    <div className="mx-auto max-w-6xl space-y-6 px-4 py-6 sm:px-6 lg:py-8">
      <header className="flex flex-col justify-between gap-4 border-b border-slate-200 pb-6 sm:flex-row sm:items-end"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-orange-700">Field assurance</p><h1 className="mt-2 text-3xl font-black tracking-tight text-slate-950">Maintenance &amp; breakdowns</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-slate-600">Monitor every active installation through the Day 1-45 durability test and respond to Early Breakdown Alarms before reliability drops.</p></div><div className="flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-black text-emerald-800"><Radio className="h-4 w-4" /> Monitoring live</div></header>
      <div className="grid gap-4 sm:grid-cols-3"><div className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-xs font-bold uppercase text-slate-500">Active installations</p><p className="mt-1 text-3xl font-black text-slate-950">12</p></div><div className="rounded-xl border border-emerald-100 bg-emerald-50 p-4"><p className="text-xs font-bold uppercase text-emerald-700">Operational</p><p className="mt-1 text-3xl font-black text-emerald-950">11</p></div><div className="rounded-xl border border-orange-100 bg-orange-50 p-4"><p className="text-xs font-bold uppercase text-orange-700">Early alarms</p><p className="mt-1 text-3xl font-black text-orange-950">1</p></div></div>
      <section className="grid gap-4">{installations.map((installation) => { const watch = installation.alarm === 'Watch'; return <article key={installation.id} className={`rounded-2xl border bg-white p-5 shadow-sm ${watch ? 'border-orange-300' : 'border-slate-200'}`}><div className="flex flex-col justify-between gap-4 md:flex-row md:items-start"><div><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-xs font-black text-blue-700">#{installation.id}</span><span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-xs font-black ${watch ? 'bg-orange-100 text-orange-800' : 'bg-emerald-100 text-emerald-800'}`}>{watch ? <AlertTriangle className="h-3.5 w-3.5" /> : <CheckCircle2 className="h-3.5 w-3.5" />}{installation.alarm}</span></div><h2 className="mt-2 text-lg font-black text-slate-950">{installation.title}</h2><p className="mt-1 text-sm text-slate-600">{installation.site} · telemetry updated {installation.updated}</p></div><div className="flex items-center gap-2 rounded-lg bg-slate-100 px-3 py-2 text-sm font-black text-slate-700"><ShieldCheck className="h-4 w-4 text-blue-700" />Day {installation.day} / 45</div></div><div className="mt-5 grid gap-4 md:grid-cols-[1fr_12rem]"><div><div className="mb-1 flex justify-between text-xs font-bold text-slate-600"><span>Durability test progress</span><span>{Math.round((installation.day / 45) * 100)}%</span></div><div className="h-3 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${watch ? 'bg-orange-500' : 'bg-emerald-500'}`} style={{ width: `${(installation.day / 45) * 100}%` }} /></div></div><div className="rounded-lg border border-slate-200 px-3 py-2"><p className="text-xs font-bold text-slate-500">Field health</p><p className={`mt-1 text-xl font-black ${watch ? 'text-orange-700' : 'text-emerald-700'}`}>{installation.health}%</p></div></div>{watch && <div className="mt-4 flex items-start gap-2 rounded-lg border border-orange-200 bg-orange-50 p-3 text-xs font-semibold leading-relaxed text-orange-900"><Wrench className="mt-0.5 h-4 w-4 shrink-0" />Early Breakdown Alarm: schedule a field inspection and record corrective action before the next telemetry window.</div>}</article>; })}</section>
    </div>
  );
}
