'use client';

import { useRef, useState } from 'react';
import { AlertTriangle, Mic, X } from 'lucide-react';

export default function BreakdownAlarmModal({ open, onClose, onConfirm }: { open: boolean; onClose: () => void; onConfirm: (description: string) => void }) {
  const [description, setDescription] = useState('');
  const inputRef = useRef<HTMLInputElement>(null);
  if (!open) return null;
  return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-slate-950/70 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="breakdown-alarm-title"><div className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl sm:p-8"><div className="flex items-start justify-between gap-4"><div className="flex items-start gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-red-100 text-red-700"><AlertTriangle className="h-6 w-6" /></span><div><h2 id="breakdown-alarm-title" className="text-xl font-black text-slate-950">Report Machine Breakdown</h2><p className="mt-1 text-xs font-bold text-red-700">Kharab Ho Gaya · emergency pilot signal</p></div></div><button type="button" onClick={onClose} aria-label="Close breakdown dialog" className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><X className="h-5 w-5" /></button></div><p className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm leading-6 text-red-950">Per USP 5: If &gt;= 3 verified citizens report breakdown within 24h, the 45-day clock freezes immediately. 48h inspection SLA + 7-day repair window triggered. Once repaired, clock resets to Day 1.</p><label className="mt-5 block text-xs font-black text-slate-800">Voice note or breakdown description</label><div className="mt-2 flex gap-2"><input ref={inputRef} value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Describe what has stopped working..." className="min-h-12 flex-1 rounded-xl border border-slate-300 px-3 text-sm text-slate-900 outline-none focus:ring-2 focus:ring-red-500" /><button type="button" onClick={() => inputRef.current?.focus()} aria-label="Start voice note" className="flex h-12 w-12 items-center justify-center rounded-xl border border-red-200 bg-red-50 text-red-700"><Mic className="h-5 w-5" /></button></div><div className="mt-6 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button type="button" onClick={onClose} className="min-h-11 rounded-xl px-4 text-sm font-bold text-slate-600 hover:bg-slate-100">Cancel</button><button type="button" onClick={() => { onConfirm(description || 'Citizen reported a machine breakdown.'); setDescription(''); }} className="min-h-11 rounded-xl bg-red-700 px-5 text-sm font-black text-white shadow-lg shadow-red-900/20 hover:bg-red-800">Confirm breakdown report</button></div></div></div>;
}