import type { FailureCase } from "./failures";

export const FAILURE_CASES: FailureCase[] = [
  {
    id: "FAIL-2023-014",
    ticketId: "JAG-3108",
    title: "Low-Cost Iron Removal Filter for High-Silica Groundwater",
    campus: "BIT Mesra",
    district: "Palamu",
    year: 2023,
    domain: "Water & Public Health",
    severity: "MINOR",
    trl: "TRL-4 (bench prototype)",
    attempted: "40 L/day gravity iron-removal unit with MS wool + aeration cascade + sand bed at two handpumps for 21 days.",
    specs: ["Flow: 40 L/day gravity feed", "Media: MS wool 2 kg + MnO2 sand 8 kg", "CapEx: Rs. 4,800/unit"],
    rootCause: "Electrochemical passivation of iron electrodes in high-silica water. Silica above 45 mg/L filmed MS wool in 9 days.",
    failureModes: ["Silica film blocked electron transfer", "Aeration undersized for pH 6.8-7.4", "Sand bed clogged"],
    recommendations: ["Pre-screen silica before iron media", "Pilot Al-anode electrocoagulation", "Weekly backwash SOP + test strip"],
    costINR: 68000,
    teamSize: 6,
  },
  {
    id: "FAIL-2023-027",
    ticketId: "JAG-3221",
    title: "Solar Dryer for Lac & Tamarind Preservation",
    campus: "Birsa Agricultural University",
    district: "Khunti",
    year: 2023,
    domain: "Agri & Forest Produce",
    severity: "MINOR",
    trl: "TRL-5 (field pilot)",
    attempted: "50 kg/batch indirect solar cabinet dryer with GI absorber and chimney draft, trialled with two FPO clusters.",
    specs: ["Capacity: 50 kg/batch", "Peak temp: 58C clear sky", "CapEx: Rs. 22,000/unit"],
    rootCause: "Hygroscopic re-absorption on humid nights. Drying 62% to 18% reversed to 34% overnight, no desiccant buffer.",
    failureModes: ["No night vapour barrier", "Draft stalled below 3 km/h", "Trays corroded by acids"],
    recommendations: ["Add desiccant tray for night hold", "Food-grade SS trays", "Re-test Oct-Mar window"],
    costINR: 91000,
    teamSize: 8,
  },
  {
    id: "FAIL-2022-041",
    ticketId: "JAG-2880",
    title: "Non-Electric Aerated Composter for 500-Student School",
    campus: "NIT Jamshedpur",
    district: "Chaibasa",
    year: 2022,
    domain: "Sanitation & Circular Economy",
    severity: "MINOR",
    trl: "TRL-4 (bench prototype)",
    attempted: "200 L twin-drum passive-aeration composter with PVC laterals and jute lid at one school for 60 days.",
    specs: ["Throughput: 8-10 kg/day", "Retention: 28 days", "CapEx: Rs. 11,500/unit"],
    rootCause: "Anaerobic channelling. Rice leachate sealed perforations, oxygen fell below 8%, phase stalled at 38C.",
    failureModes: ["Leachate blocked air laterals", "No brown-waste dosing", "Jute lid held rainwater"],
    recommendations: ["Mandate 1:2 green-brown dosing", "Leachate-drain plinth + tap", "Sloped FRP rain cap"],
    costINR: 54000,
    teamSize: 5,
  },
];
export const FAILURE_CASES_MAJOR: FailureCase[] = [
  {
    id: "FAIL-2023-052",
    ticketId: "JAG-3190",
    title: "Tussar Silk Reeling Effluent Bio-Filter",
    campus: "BIT Mesra",
    district: "Godda",
    year: 2023,
    domain: "Livelihood & Textiles",
    severity: "MINOR",
    trl: "TRL-4 (bench prototype)",
    attempted: "Gravel + biochar + vetiver filter for 300 L/day effluent, run 45 days at one artisan centre.",
    specs: ["Flow: 300 L/day", "Media: gravel 0.4 m3 + biochar 120 kg", "CapEx: Rs. 18,000/unit"],
    rootCause: "Sericin shock loading. COD spiked to 4,800 mg/L (3x design), stripping biofilm in 72 hours.",
    failureModes: ["Ignored batch spikes", "Biochar saturated in 18 days", "No equalisation tank"],
    recommendations: ["Add 500 L equalisation tank", "Size biochar for peak COD", "Recover sericin to fund O&M"],
    costINR: 47000,
    teamSize: 6,
  },
  {
    id: "FAIL-2022-058",
    ticketId: "JAG-2744",
    title: "Fluoride Remediation Pilot for 20-Hamlet Cluster",
    campus: "IIT ISM Dhanbad + BIT Mesra",
    district: "Garhwa",
    year: 2022,
    domain: "Water & Public Health",
    severity: "MAJOR",
    trl: "TRL-6 (hamlet deployment)",
    attempted: "Retrofit of PHED alumina fluoride plant with solar pumping and VLE O&M across 6 hamlets, 5 months.",
    specs: ["Flow: 2,000 L/day", "Fluoride: 2.4-4.1 mg/L", "Outlay: Rs. 8.4 Lakh"],
    rootCause: "Systemic regeneration failure. Alumina never regenerated after contractor exit; breakthrough at day 34.",
    failureModes: ["No regeneration logistics", "Zero field test kits", "Solar pump oversized 2x"],
    recommendations: ["Pan-India statement: low-regeneration media", "Test-kit + regeneration escrow", "Split energy/treatment budgets"],
    costINR: 840000,
    teamSize: 14,
  },
  {
    id: "FAIL-2024-003",
    ticketId: "JAG-3402",
    title: "5 MT Solar Cold Room for Lac Cold Chain",
    campus: "NIT Jamshedpur",
    district: "Khunti",
    year: 2024,
    domain: "Agri & Forest Produce",
    severity: "MAJOR",
    trl: "TRL-6 (cluster pilot)",
    attempted: "5 MT solar cold room (3 kWp + 10 kWh) with IoT metering for one summer lac season.",
    specs: ["Capacity: 5 MT at 4-8C", "Solar: 3 kWp + 10 kWh", "CapEx: Rs. 6.2 Lakh"],
    rootCause: "Thermal-load miscalculation at 44C ambient. Compressor exceeded battery by 3.2 hrs/day; nights hit 14C.",
    failureModes: ["Modelled at 32C not 44C", "40+ door openings, no curtain", "Tariff by weight hid losses"],
    recommendations: ["Pan-India statement: phase-change buffer", "Model 46C + strip curtains", "Tariff on cooling-hours + SLA"],
    costINR: 620000,
    teamSize: 11,
  },
];

export const ALL_FAILURE_CASES: FailureCase[] = [...FAILURE_CASES, ...FAILURE_CASES_MAJOR];

